import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import MainContent from '@/components/MainContent'
import MainLayout from '@/layouts/MainLayout'
import AuthForm from '@/components/AuthForm'
import { NextPage } from 'next'

const isAuth = false
interface IHomeProps {
  data: any
}

const Home: NextPage<IHomeProps> = ({ data }) => {
  console.log(data, 'HOME PAGE')

  return (
    <>
      <Head>
        <title>Login Form App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <MainLayout>{isAuth ? <MainContent /> : <AuthForm />}</MainLayout>
      </main>
    </>
  )
}

export default Home
